### ISSUE TITLE
Do you think Parameters Sharing worked efficiently in CNN?

### ISSUE THREAD

**Issue by choqueen** [bkj/ripenet#4] opened 2018-04-03 09:13 UTC
I don't think it can finish search architectures of CNN in 11.5 hours, because the parameters sharing is not as efficient as in RNN.

**Comment by bkj** [comment] 2018-04-03 13:30
Can you explain what you mean? They say it works in the paper, so presumably it's true.  I haven't been able to reproduce their results, but presumably that's because of hyperparameter choices / unspecified parts of the architecture search.

**Comment by choqueen** [comment] 2018-04-04 03:05
I'm implementing on the micro-CNN portion of the paper, but the train duration is more than 20 times of it metioned by the paper.(310 each architection) It is nearly 20 epoches per hour, comparing with 20 eppoches per minute in this paper. I have no idea with this difference. Can you help to list your time cost of training? Thank you very much!

**Comment by bkj** [comment] 2018-04-04 03:53
Hardware would be the number 1 thing -- are you using a GPU?

Otherwise, runtimes are very implementation-specific, so I'm not going to be able to help you without knowing something more specific.  

If you haven't seen it, the authors of the paper released [their code](https://github.com/melodyguan/enas) -- I'd suggest taking a look at that as a first step.

**Comment by bkj** [comment] 2018-05-07 03:12
Going to close this -- feel free to reopen if you have further questions.

**Closed by bkj** 2018-05-07 03:12 UTC
